---

- name: Set max open files for nginx service
  become: yes
  ini_file:
    option: LimitNOFILE
    path: /etc/systemd/system/nginx.service.d/override.conf
    section: Service
    value: "{{ sansible_nginx_worker_rlimit_nofile }}"
    mode: 0644
  register: sansible_nginx_systemd_conf_file

- name: Ensure nginx service is updated
  become: yes
  systemd:
    daemon_reload: yes
  when: sansible_nginx_systemd_conf_file.changed
  tags:
    - skip_ansible_lint

- name: Configure nginx service
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Removes default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: Configure nginx status include
  become: yes
  template:
    src: includes/nginx_status.j2
    dest: /etc/nginx/includes/nginx_status
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
